// <auto-generated />
using System;
using BaiThucHanh01_Nhom2_DinhDuy23810310435;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaiThucHanh01_Nhom2_DinhDuy23810310435.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405090632_ThemCacBang")]
    partial class ThemCacBang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DonGia")
                        .HasColumnType("double precision");

                    b.Property<int>("DonHangId")
                        .HasColumnType("integer");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fashion T-Shirts",
                            NameVN = "Áo Thời Trang"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Denim Jeans",
                            NameVN = "Quần Denim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Luxury Accessories",
                            NameVN = "Phụ Kiện Cao Cấp"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Winter Jackets",
                            NameVN = "Áo Khoác Thu Đông"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sneakers",
                            NameVN = "Giày Sneaker"
                        });
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KhachHangId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TongTien")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.KhachHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("boolean");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("integer");

                    b.Property<string>("DuongDanAnh")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GiaGoc")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFeatureProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("boolean");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("integer");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 82.5666526963779m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #001"
                        },
                        new
                        {
                            Id = 2,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 97.4344948383209m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #002"
                        },
                        new
                        {
                            Id = 3,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 103.873985039012m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #003"
                        },
                        new
                        {
                            Id = 4,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 25.0635060570498m,
                            GiaGoc = 182m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 7,
                            TenSanPham = "Sản phẩm Trendy #004"
                        },
                        new
                        {
                            Id = 5,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 37.7314857559891m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #005"
                        },
                        new
                        {
                            Id = 6,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/no-image.png",
                            GiaBan = 36.3217230654888m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #006"
                        },
                        new
                        {
                            Id = 7,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 142.164979958518m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #007"
                        },
                        new
                        {
                            Id = 8,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 126.459751408296m,
                            GiaGoc = 220m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 20,
                            TenSanPham = "Sản phẩm Trendy #008"
                        },
                        new
                        {
                            Id = 9,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/no-image.png",
                            GiaBan = 44.251229848364m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #009"
                        },
                        new
                        {
                            Id = 10,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 44.4512711113558m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #010"
                        },
                        new
                        {
                            Id = 11,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 47.7406541713237m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #011"
                        },
                        new
                        {
                            Id = 12,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 131.571810163358m,
                            GiaGoc = 196m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 5,
                            TenSanPham = "Sản phẩm Trendy #012"
                        },
                        new
                        {
                            Id = 13,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 42.2725324538874m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #013"
                        },
                        new
                        {
                            Id = 14,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 36.772724770835m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #014"
                        },
                        new
                        {
                            Id = 15,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 12.3003112931272m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #015"
                        },
                        new
                        {
                            Id = 16,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 100.300916974573m,
                            GiaGoc = 179m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 7,
                            TenSanPham = "Sản phẩm Trendy #016"
                        },
                        new
                        {
                            Id = 17,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 14.4112652616628m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #017"
                        },
                        new
                        {
                            Id = 18,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 62.9335274584282m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #018"
                        },
                        new
                        {
                            Id = 19,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 129.262443874154m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #019"
                        },
                        new
                        {
                            Id = 20,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 83.2347803191444m,
                            GiaGoc = 244m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 26,
                            TenSanPham = "Sản phẩm Trendy #020"
                        },
                        new
                        {
                            Id = 21,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 39.3377116813034m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #021"
                        },
                        new
                        {
                            Id = 22,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 13.9195446143483m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #022"
                        },
                        new
                        {
                            Id = 23,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 45.4460506795189m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #023"
                        },
                        new
                        {
                            Id = 24,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 112.309663826744m,
                            GiaGoc = 162m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 26,
                            TenSanPham = "Sản phẩm Trendy #024"
                        },
                        new
                        {
                            Id = 25,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 104.650879437873m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #025"
                        },
                        new
                        {
                            Id = 26,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 63.1278887428939m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #026"
                        },
                        new
                        {
                            Id = 27,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 111.465947394942m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #027"
                        },
                        new
                        {
                            Id = 28,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 67.2226073323854m,
                            GiaGoc = 187m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 20,
                            TenSanPham = "Sản phẩm Trendy #028"
                        },
                        new
                        {
                            Id = 29,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 78.7643228195441m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #029"
                        },
                        new
                        {
                            Id = 30,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 49.9071140298187m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #030"
                        },
                        new
                        {
                            Id = 31,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 122.229737555249m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #031"
                        },
                        new
                        {
                            Id = 32,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 11.7718757087234m,
                            GiaGoc = 247m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 7,
                            TenSanPham = "Sản phẩm Trendy #032"
                        },
                        new
                        {
                            Id = 33,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 49.306020063025m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #033"
                        },
                        new
                        {
                            Id = 34,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/no-image.png",
                            GiaBan = 42.3697534172655m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #034"
                        },
                        new
                        {
                            Id = 35,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 81.824613135692m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #035"
                        },
                        new
                        {
                            Id = 36,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 120.834045317878m,
                            GiaGoc = 197m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 13,
                            TenSanPham = "Sản phẩm Trendy #036"
                        },
                        new
                        {
                            Id = 37,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 136.836247318814m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #037"
                        },
                        new
                        {
                            Id = 38,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 68.5603658643366m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #038"
                        },
                        new
                        {
                            Id = 39,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 83.3490706888722m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #039"
                        },
                        new
                        {
                            Id = 40,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 74.2012177501811m,
                            GiaGoc = 203m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 27,
                            TenSanPham = "Sản phẩm Trendy #040"
                        },
                        new
                        {
                            Id = 41,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 48.2567255321223m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #041"
                        },
                        new
                        {
                            Id = 42,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 14.0856277784731m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #042"
                        },
                        new
                        {
                            Id = 43,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 20.3133003531551m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #043"
                        },
                        new
                        {
                            Id = 44,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 145.200933218562m,
                            GiaGoc = 190m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 8,
                            TenSanPham = "Sản phẩm Trendy #044"
                        },
                        new
                        {
                            Id = 45,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 28.6211149918945m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #045"
                        },
                        new
                        {
                            Id = 46,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/no-image.png",
                            GiaBan = 141.515962607933m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #046"
                        },
                        new
                        {
                            Id = 47,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 27.7184445358433m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #047"
                        },
                        new
                        {
                            Id = 48,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 99.0858500185822m,
                            GiaGoc = 222m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 16,
                            TenSanPham = "Sản phẩm Trendy #048"
                        },
                        new
                        {
                            Id = 49,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 63.255881000895m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #049"
                        },
                        new
                        {
                            Id = 50,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 18.7815769718874m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #050"
                        },
                        new
                        {
                            Id = 51,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 108.017451254659m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #051"
                        },
                        new
                        {
                            Id = 52,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 76.3582943227879m,
                            GiaGoc = 225m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 20,
                            TenSanPham = "Sản phẩm Trendy #052"
                        },
                        new
                        {
                            Id = 53,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/no-image.png",
                            GiaBan = 149.793083512128m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #053"
                        },
                        new
                        {
                            Id = 54,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 13.7900130393868m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #054"
                        },
                        new
                        {
                            Id = 55,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 37.5843215438464m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #055"
                        },
                        new
                        {
                            Id = 56,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 68.8523015113791m,
                            GiaGoc = 183m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 21,
                            TenSanPham = "Sản phẩm Trendy #056"
                        },
                        new
                        {
                            Id = 57,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 10.8457074113403m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #057"
                        },
                        new
                        {
                            Id = 58,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 127.337317318347m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #058"
                        },
                        new
                        {
                            Id = 59,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 89.393847711102m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #059"
                        },
                        new
                        {
                            Id = 60,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 136.98157954448m,
                            GiaGoc = 190m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 21,
                            TenSanPham = "Sản phẩm Trendy #060"
                        },
                        new
                        {
                            Id = 61,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 26.0838570450823m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #061"
                        },
                        new
                        {
                            Id = 62,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 86.4091370144902m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #062"
                        },
                        new
                        {
                            Id = 63,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 75.2736937102274m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #063"
                        },
                        new
                        {
                            Id = 64,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 146.379690988632m,
                            GiaGoc = 178m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 7,
                            TenSanPham = "Sản phẩm Trendy #064"
                        },
                        new
                        {
                            Id = 65,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 101.98102490929m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #065"
                        },
                        new
                        {
                            Id = 66,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 57.1152539072164m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #066"
                        },
                        new
                        {
                            Id = 67,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/no-image.png",
                            GiaBan = 45.6799230406433m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #067"
                        },
                        new
                        {
                            Id = 68,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 119.068699416271m,
                            GiaGoc = 206m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 14,
                            TenSanPham = "Sản phẩm Trendy #068"
                        },
                        new
                        {
                            Id = 69,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 32.0282925749329m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #069"
                        },
                        new
                        {
                            Id = 70,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 32.7613927320397m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #070"
                        },
                        new
                        {
                            Id = 71,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 104.27865616152m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #071"
                        },
                        new
                        {
                            Id = 72,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 39.8347924821241m,
                            GiaGoc = 227m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 16,
                            TenSanPham = "Sản phẩm Trendy #072"
                        },
                        new
                        {
                            Id = 73,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 38.863495943073m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #073"
                        },
                        new
                        {
                            Id = 74,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 87.0044855726904m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #074"
                        },
                        new
                        {
                            Id = 75,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 67.7841409946718m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #075"
                        },
                        new
                        {
                            Id = 76,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 49.389296602639m,
                            GiaGoc = 245m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 29,
                            TenSanPham = "Sản phẩm Trendy #076"
                        },
                        new
                        {
                            Id = 77,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 132.000035323668m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #077"
                        },
                        new
                        {
                            Id = 78,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 67.8545553348281m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #078"
                        },
                        new
                        {
                            Id = 79,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 40.0362193533388m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #079"
                        },
                        new
                        {
                            Id = 80,
                            DanhMucId = 5,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 20.5748195795225m,
                            GiaGoc = 214m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 23,
                            TenSanPham = "Sản phẩm Trendy #080"
                        },
                        new
                        {
                            Id = 81,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 61.5595483018828m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #081"
                        },
                        new
                        {
                            Id = 82,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 88.0396794234587m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #082"
                        },
                        new
                        {
                            Id = 83,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 148.756436001862m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #083"
                        },
                        new
                        {
                            Id = 84,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 114.240829653219m,
                            GiaGoc = 236m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 29,
                            TenSanPham = "Sản phẩm Trendy #084"
                        },
                        new
                        {
                            Id = 85,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 100.288360191178m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #085"
                        },
                        new
                        {
                            Id = 86,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 80.982438567552m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #086"
                        },
                        new
                        {
                            Id = 87,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 31.7821621605112m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #087"
                        },
                        new
                        {
                            Id = 88,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 102.253672308407m,
                            GiaGoc = 217m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 24,
                            TenSanPham = "Sản phẩm Trendy #088"
                        },
                        new
                        {
                            Id = 89,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 120.266886463513m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #089"
                        },
                        new
                        {
                            Id = 90,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 87.0236673359869m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #090"
                        },
                        new
                        {
                            Id = 91,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 144.861822716827m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #091"
                        },
                        new
                        {
                            Id = 92,
                            DanhMucId = 1,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 97.1176154995885m,
                            GiaGoc = 207m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 13,
                            TenSanPham = "Sản phẩm Trendy #092"
                        },
                        new
                        {
                            Id = 93,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 43.7034568640885m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #093"
                        },
                        new
                        {
                            Id = 94,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 120.430607471816m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #094"
                        },
                        new
                        {
                            Id = 95,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 27.7025196252868m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #095"
                        },
                        new
                        {
                            Id = 96,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 31.4675131758989m,
                            GiaGoc = 226m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 6,
                            TenSanPham = "Sản phẩm Trendy #096"
                        },
                        new
                        {
                            Id = 97,
                            DanhMucId = 2,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 35.465348050215m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #097"
                        },
                        new
                        {
                            Id = 98,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 99.5277594227939m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #098"
                        },
                        new
                        {
                            Id = 99,
                            DanhMucId = 3,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 145.183233491696m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm Trendy #099"
                        },
                        new
                        {
                            Id = 100,
                            DanhMucId = 4,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 82.386532862385m,
                            GiaGoc = 220m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 26,
                            TenSanPham = "Sản phẩm Trendy #100"
                        });
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.DonHang", b =>
                {
                    b.HasOne("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.SanPham", b =>
                {
                    b.HasOne("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
