// <auto-generated />
using BaiThucHanh01_Nhom2_DinhDuy23810310435;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaiThucHanh01_Nhom2_DinhDuy23810310435.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324082853_Add100SanPham1")]
    partial class Add100SanPham1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GiaGoc")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFeatureProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("boolean");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("integer");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 51.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 1"
                        },
                        new
                        {
                            Id = 2,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 52.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 2"
                        },
                        new
                        {
                            Id = 3,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 53.0m,
                            GiaGoc = 73.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 3"
                        },
                        new
                        {
                            Id = 4,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 54.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 4"
                        },
                        new
                        {
                            Id = 5,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 55.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 5"
                        },
                        new
                        {
                            Id = 6,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 56.0m,
                            GiaGoc = 76.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 6"
                        },
                        new
                        {
                            Id = 7,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 57.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 7"
                        },
                        new
                        {
                            Id = 8,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 58.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 8"
                        },
                        new
                        {
                            Id = 9,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 59.0m,
                            GiaGoc = 79.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 9"
                        },
                        new
                        {
                            Id = 10,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 60.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 10"
                        },
                        new
                        {
                            Id = 11,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 61.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 11"
                        },
                        new
                        {
                            Id = 12,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 62.0m,
                            GiaGoc = 82.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 12"
                        },
                        new
                        {
                            Id = 13,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 63.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 13"
                        },
                        new
                        {
                            Id = 14,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 64.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 14"
                        },
                        new
                        {
                            Id = 15,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 65.0m,
                            GiaGoc = 85.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 15"
                        },
                        new
                        {
                            Id = 16,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 66.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 16"
                        },
                        new
                        {
                            Id = 17,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 67.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 17"
                        },
                        new
                        {
                            Id = 18,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 68.0m,
                            GiaGoc = 88.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 18"
                        },
                        new
                        {
                            Id = 19,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 69.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 19"
                        },
                        new
                        {
                            Id = 20,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 50.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 20"
                        },
                        new
                        {
                            Id = 21,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 51.0m,
                            GiaGoc = 71.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 21"
                        },
                        new
                        {
                            Id = 22,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 52.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 22"
                        },
                        new
                        {
                            Id = 23,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 53.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 23"
                        },
                        new
                        {
                            Id = 24,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 54.0m,
                            GiaGoc = 74.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 24"
                        },
                        new
                        {
                            Id = 25,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 55.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 25"
                        },
                        new
                        {
                            Id = 26,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 56.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 26"
                        },
                        new
                        {
                            Id = 27,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 57.0m,
                            GiaGoc = 77.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 27"
                        },
                        new
                        {
                            Id = 28,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 58.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 28"
                        },
                        new
                        {
                            Id = 29,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 59.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 29"
                        },
                        new
                        {
                            Id = 30,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 60.0m,
                            GiaGoc = 80.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 30"
                        },
                        new
                        {
                            Id = 31,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 61.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 31"
                        },
                        new
                        {
                            Id = 32,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 62.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 32"
                        },
                        new
                        {
                            Id = 33,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 63.0m,
                            GiaGoc = 83.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 33"
                        },
                        new
                        {
                            Id = 34,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 64.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 34"
                        },
                        new
                        {
                            Id = 35,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 65.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 35"
                        },
                        new
                        {
                            Id = 36,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 66.0m,
                            GiaGoc = 86.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 36"
                        },
                        new
                        {
                            Id = 37,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 67.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 37"
                        },
                        new
                        {
                            Id = 38,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 68.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 38"
                        },
                        new
                        {
                            Id = 39,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 69.0m,
                            GiaGoc = 89.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 39"
                        },
                        new
                        {
                            Id = 40,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 50.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 40"
                        },
                        new
                        {
                            Id = 41,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 51.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 41"
                        },
                        new
                        {
                            Id = 42,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 52.0m,
                            GiaGoc = 72.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 42"
                        },
                        new
                        {
                            Id = 43,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 53.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 43"
                        },
                        new
                        {
                            Id = 44,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 54.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 44"
                        },
                        new
                        {
                            Id = 45,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 55.0m,
                            GiaGoc = 75.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 45"
                        },
                        new
                        {
                            Id = 46,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 56.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 46"
                        },
                        new
                        {
                            Id = 47,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 57.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 47"
                        },
                        new
                        {
                            Id = 48,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 58.0m,
                            GiaGoc = 78.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 48"
                        },
                        new
                        {
                            Id = 49,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 59.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 49"
                        },
                        new
                        {
                            Id = 50,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 60.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 50"
                        },
                        new
                        {
                            Id = 51,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 61.0m,
                            GiaGoc = 81.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 51"
                        },
                        new
                        {
                            Id = 52,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 62.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 52"
                        },
                        new
                        {
                            Id = 53,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 63.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 53"
                        },
                        new
                        {
                            Id = 54,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 64.0m,
                            GiaGoc = 84.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 54"
                        },
                        new
                        {
                            Id = 55,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 65.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 55"
                        },
                        new
                        {
                            Id = 56,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 66.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 56"
                        },
                        new
                        {
                            Id = 57,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 67.0m,
                            GiaGoc = 87.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 57"
                        },
                        new
                        {
                            Id = 58,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 68.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 58"
                        },
                        new
                        {
                            Id = 59,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 69.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 59"
                        },
                        new
                        {
                            Id = 60,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 50.0m,
                            GiaGoc = 70.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 60"
                        },
                        new
                        {
                            Id = 61,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 51.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 61"
                        },
                        new
                        {
                            Id = 62,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 52.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 62"
                        },
                        new
                        {
                            Id = 63,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 53.0m,
                            GiaGoc = 73.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 63"
                        },
                        new
                        {
                            Id = 64,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 54.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 64"
                        },
                        new
                        {
                            Id = 65,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 55.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 65"
                        },
                        new
                        {
                            Id = 66,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 56.0m,
                            GiaGoc = 76.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 66"
                        },
                        new
                        {
                            Id = 67,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 57.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 67"
                        },
                        new
                        {
                            Id = 68,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 58.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 68"
                        },
                        new
                        {
                            Id = 69,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 59.0m,
                            GiaGoc = 79.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 69"
                        },
                        new
                        {
                            Id = 70,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 60.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 70"
                        },
                        new
                        {
                            Id = 71,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 61.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 71"
                        },
                        new
                        {
                            Id = 72,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 62.0m,
                            GiaGoc = 82.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 72"
                        },
                        new
                        {
                            Id = 73,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 63.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 73"
                        },
                        new
                        {
                            Id = 74,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 64.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 74"
                        },
                        new
                        {
                            Id = 75,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 65.0m,
                            GiaGoc = 85.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 75"
                        },
                        new
                        {
                            Id = 76,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 66.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 76"
                        },
                        new
                        {
                            Id = 77,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 67.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 77"
                        },
                        new
                        {
                            Id = 78,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 68.0m,
                            GiaGoc = 88.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 78"
                        },
                        new
                        {
                            Id = 79,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 69.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 79"
                        },
                        new
                        {
                            Id = 80,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 50.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 80"
                        },
                        new
                        {
                            Id = 81,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 51.0m,
                            GiaGoc = 71.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 81"
                        },
                        new
                        {
                            Id = 82,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 52.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 82"
                        },
                        new
                        {
                            Id = 83,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 53.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 83"
                        },
                        new
                        {
                            Id = 84,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 54.0m,
                            GiaGoc = 74.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 84"
                        },
                        new
                        {
                            Id = 85,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 55.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 85"
                        },
                        new
                        {
                            Id = 86,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 56.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 86"
                        },
                        new
                        {
                            Id = 87,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 57.0m,
                            GiaGoc = 77.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 87"
                        },
                        new
                        {
                            Id = 88,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 58.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 88"
                        },
                        new
                        {
                            Id = 89,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 59.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 89"
                        },
                        new
                        {
                            Id = 90,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 60.0m,
                            GiaGoc = 80.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 90"
                        },
                        new
                        {
                            Id = 91,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 61.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 91"
                        },
                        new
                        {
                            Id = 92,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 62.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 92"
                        },
                        new
                        {
                            Id = 93,
                            DuongDanAnh = "/lib/product-6.png",
                            GiaBan = 63.0m,
                            GiaGoc = 83.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 93"
                        },
                        new
                        {
                            Id = 94,
                            DuongDanAnh = "/lib/product-7.png",
                            GiaBan = 64.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 94"
                        },
                        new
                        {
                            Id = 95,
                            DuongDanAnh = "/lib/product-8.png",
                            GiaBan = 65.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 95"
                        },
                        new
                        {
                            Id = 96,
                            DuongDanAnh = "/lib/product-1.png",
                            GiaBan = 66.0m,
                            GiaGoc = 86.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 96"
                        },
                        new
                        {
                            Id = 97,
                            DuongDanAnh = "/lib/product-2.png",
                            GiaBan = 67.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 97"
                        },
                        new
                        {
                            Id = 98,
                            DuongDanAnh = "/lib/product-3.png",
                            GiaBan = 68.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 98"
                        },
                        new
                        {
                            Id = 99,
                            DuongDanAnh = "/lib/product-4.png",
                            GiaBan = 69.0m,
                            GiaGoc = 89.0m,
                            IsFeatureProduct = false,
                            IsNewProduct = false,
                            IsOnSale = true,
                            PhanTramGiam = 15,
                            TenSanPham = "Sản phẩm thời trang mẫu 99"
                        },
                        new
                        {
                            Id = 100,
                            DuongDanAnh = "/lib/product-5.png",
                            GiaBan = 50.0m,
                            IsFeatureProduct = true,
                            IsNewProduct = true,
                            IsOnSale = false,
                            TenSanPham = "Sản phẩm thời trang mẫu 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
