// <auto-generated />
using BaiThucHanh01_Nhom2_DinhDuy23810310435;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaiThucHanh01_Nhom2_DinhDuy23810310435.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324070348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaiThucHanh01_Nhom2_DinhDuy23810310435.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GiaGoc")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFeatureProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewProduct")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("boolean");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("integer");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
